### ISSUE TITLE
Removing domain name in get_tango_host causes problems

### ISSUE THREAD

**Issue by TNoga0** [tango-controls/fandango#16]
Hello, while updating my PANIC configuration I found a fragment of code that is causing trouble and preventing me from connecting with the database:
https://github.com/tango-controls/fandango/blob/4f9fdf9c0d024de0c7b391d264728903ee8603f5/fandango/tango/defaults.py#L226-L232
It cuts out the domain name from tango host, leaving only the first word, which, in result, causes my script to crash due to the method not returning a proper tango host. Removing the line 232 and simply passing when code enters elif fixes the problem in my case.
I don't know if it is a deliberate action, but in a few cases, at least at SOLARIS, there is need for a full tango host address, so a way to keep it is a whole is needed.

Regards
Tomasz Noga

**Comment by sergirubio** [comment]
Hi Tomasz,

There are two solutions for that. First one is to set the USE_FQDN variable to True before importing panic. It will guarantee always using the "full hostname".

import fandango.tango.defaults
fandango.tango.defaults.USE_FQDN = True

For the other solution I'm just uploading a patch to github. Instead of assuming FQDN as False by default; I will let the Database/Environment to choose it. It means that if TANGO_HOST variable contains a full hostname, it will be respected. (so simply ensure that your TANGO_HOST env variable is set and everything will work).

Please, get last sources and try again

Sergi
